### ISSUE TITLE
Stuck at 93%

### ISSUE THREAD

**Issue by Zhaoyang-Jia** [NotJoeMartinez/chess-insights#57]
There seems to be an issue where the fetching data is getting stuck.

![Chess_Insights_Issue](https://github.com/user-attachments/assets/51262018-78df-4a9a-8218-6408a9ceb357)

**Comment by Zhaoyang-Jia** [comment]
I've tried using different machines, different browsers, and clearing cookies. None seems to resolve this issue. 
Thank you for your time.

**Comment by NotJoeMartinez** [comment]
Thanks for reporting this working on a solution

**Comment by NotJoeMartinez** [comment]
Just fixed the issue, the problem was with a change in the /pub/player/{username}/games/{yyyy}/{mm} API endpoint. The value for the url key used to be `https://www.chess.com/game/live/[long integer]` it's now `https://www.chess.com/game/uuid` although the legacy game url is still present in the pgn data and will still render the original game. 

`chess.com` has been making some updates to their API so feel free to make another issue if you find another bug. Thanks again for reporting this.

Fix commit: https://github.com/NotJoeMartinez/chess-insights/commit/387de439d8468189521f88615a154effd2496e96
